### ISSUE TITLE
Nyamrup frontend home page

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/nyamrub-web#11]
### Description
Develop nyamrup's new design's hompage

### Subtask

- [x] Add navigation in header
- [x] Create scrolling page with framer
- [x] Add monlam font
