### ISSUE TITLE
Nyamrup new design changes

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/nyamrub-web#12]
### description
As nyamup's new design is ready, Need to modify the following changes.

### subtask

- [x] Update route for contribution, about and leaderboard
- [x] Navigation & Header
- [x] Contribution Section
- [x] Validation Section
- [x] About Section
- [ ] Leaderboard
- [x] General UI Components (Buttons, progress bar, cards)
- [x] Footer
- [x] Clean up the unused components
